stages:
  - build-app

build app:
  stage: build-app
  image: node:8
  script:
    - npm run build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - .next
      - build
    expire_in: 1 day